aws_region = "ap-northeast-2"
db_instance_class = "db.t3.micro"
db_name = "simter"
db_username = "admin"
db_password = "tlaxjtkfkdgo!"  
ami_id = "ami-040c33c6a51fd5d96"
instance_type = "t2.micro"
pem_key_path = "~/.ssh/gitluvsimter.pem"
